name: Sync Fork

on:
  push:
  schedule:
    - cron: '*/3 * * * *'
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: TG908/fork-sync@v2.0.10
        with:
          github_token: ${{ secrets.SYNC_TOKEN }}
          owner: Loyalsoldier
          head: master
          base: master
